apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rabbitmq-credentials-apps.yaml
  - rabbitmq-credentials-messaging.yaml
  - postgresql-credentials-apps.yaml
  - postgresql-credentials-database.yaml
  - grafana-credentials.yaml
  - elasticsearch-master-credentials.yaml
