elasticsearch:
  clusterName: "elasticsearch"
  nodeGroup: "master"

  roles: [master, data, ingest]
  replicas: 1
  minimumMasterNodes: 1

  createCert: true
  protocol: https

  clusterHealthCheckParams: "wait_for_status=yellow&timeout=60s"

  persistence:
    enabled: false

  esJavaOpts: "-Xms512m -Xmx512m"

  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  antiAffinity: "soft"

  sysctlInitContainer:
    enabled: true
  sysctlVmMaxMapCount: 262144

  secret:
    enabled: false

  extraEnvs:
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: username
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password
