clusterName: "elasticsearch"
nodeGroup: "master"

roles: [master, data, ingest]
replicas: 1
minimumMasterNodes: 1

# REQUIRED for elastic/kibana chart hooks:
createCert: true
protocol: https

# 1-node lab: don't wait for green
clusterHealthCheckParams: "wait_for_status=yellow&timeout=30s"

# readinessProbe:
#   successThreshold: 1
#   initialDelaySeconds: 20
#   periodSeconds: 10
#   timeoutSeconds: 5
#   failureThreshold: 6


persistence:
  enabled: false

esJavaOpts: "-Xms512m -Xmx512m"
resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

antiAffinity: "soft"

sysctlInitContainer:
  enabled: true
sysctlVmMaxMapCount: 262144

secret:
  enabled: false

extraEnvs:
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password
