apiVersion: v2
name: postgres-exporter-wrapper
version: 0.1.0
dependencies:
  - name: prometheus-postgres-exporter
    version: "7.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
