apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-platform-helm
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: rabbitmq
            path: k8s/charts/rabbitmq-wrapper
            ns: messaging
            wave: "20"
            valuesFile: ../../values/dev/rabbitmq.yaml

          - name: postgresql
            path: k8s/charts/postgresql-wrapper
            ns: database
            wave: "20"
            valuesFile: ../../values/dev/postgresql.yaml

          - name: order-api
            path: k8s/charts/order-api-chart
            ns: apps
            wave: "60"
            valuesFile: ../../values/dev/order-api.yaml

          - name: payment-service
            path: k8s/charts/payment-service-chart
            ns: apps
            wave: "60"
            valuesFile: ../../values/dev/payment-service.yaml

          - name: kube-prom-stack
            path: k8s/charts/kube-prom-stack-wrapper
            ns: monitoring
            wave: "30"
            valuesFile: ../../values/dev/kube-prom-stack.yaml

          - name: postgres-exporter
            path: k8s/charts/postgres-exporter-wrapper
            ns: database
            wave: "31"
            valuesFile: ../../monitoring/prom-exporters/postgresql-exporter.yaml

          - name: fluentbit
            path: k8s/charts/fluentbit-wrapper
            ns: logging
            wave: "40"
            valuesFile: ../../values/dev/fluentbit.yaml

          - name: elasticsearch
            path: k8s/charts/elasticsearch-wrapper
            ns: logging
            wave: "41"
            valuesFile: ../../values/dev/elasticsearch.yaml

          - name: kibana
            path: k8s/charts/kibana-wrapper
            ns: logging
            wave: "45"
            valuesFile: ../../values/dev/kibana.yaml

  template:
    metadata:
      name: dev-{{name}}
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/rtzi-hub/rabbitmq-ordering-platform.git
        targetRevision: dev
        path: "{{path}}"
        helm:
          releaseName: "{{name}}"     # keeps release names stable
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ns}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
