{
 "title": "K8s & Platform Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Pods Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods Count Each Namespcae",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Nodes Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  kube_node_status_condition{\r\n    condition=\"Ready\",\r\n    status=\"true\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_status_phase{phase=\"Running\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Rabbitmq",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"messaging\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Application",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"apps\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory DB",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"database\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 -\r\n  (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU rabbitmq",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"messaging\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }[5m])\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Application",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"apps\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }[5m])\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU DB",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"database\",\r\n    container!=\"POD\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }[5m])\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])\r\n)\r\n/\r\nsum by (instance) (\r\n  rate(node_cpu_seconds_total[5m])\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}